### ISSUE TITLE
Write a simple how to use this node ?

### ISSUE THREAD

**Issue by slamer59** [minhlucvan/n8n-nodes-notionmd#1]
Hello, 
First, thanks for sharing this. I was thinking of writing one like this one : https://pypi.org/project/md2notion/

What I am missing is which node it should push to ?
- Official Notion n8n node ? It seems tricky to map types since the UI change depedning on the type. 
- Or basic REST API pointing to notion like : https://developers.notion.com/reference/update-a-block

Regards :+1:

**Comment by slamer59** [comment]
This is one solution with HTTP : 

Tips : Go to Notion API documentation and copy the **curl** command and import in **HTTP Node**

![image](https://github.com/minhlucvan/n8n-nodes-notionmd/assets/25283272/475b8081-cec3-4738-810e-8bc9aebce9fb)


```
{
  "meta": {
    "instanceId": "8df17e23ee8edef0742b7feba18d9fbb0edcb67012900891125cfa4e602d6052"
  },
  "nodes": [
    {
      "parameters": {
        "input": "={{ $json.article }} ",
        "outputKey": "children"
      },
      "id": "37d4c973-d155-4860-8c70-69826a0cedd0",
      "name": "Notion MD",
      "type": "n8n-nodes-notionmd.notionMd",
      "typeVersion": 1,
      "position": [
        1620,
        80
      ]
    },
    {
      "parameters": {
        "method": "PATCH",
        "url": "https://api.notion.com/v1/blocks/XXXX-XXX-XXX-XXX-XXXX/children",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Notion-Version",
              "value": "2022-06-28"
            },
            {
              "name": "Authorization",
              "value": "Bearer XXXX"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\"children\": {{ JSON.stringify($json.children) }}}",
        "options": {}
      },
      "id": "8f3e4062-44b4-4ac0-b850-769ce7778d94",
      "name": "Add Notion Blocks",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1880,
        80
      ]
    }
  ],
  "connections": {
    "Notion MD": {
      "main": [
        [
          {
            "node": "Add Notion Blocks",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by pooriaarab** [comment]
@slamer59 can you please share a sample of your notion to markdown? Like how the json input for it is. I was able to get markdown to notion work but not the opposite way. 

![image](https://github.com/minhlucvan/n8n-nodes-notionmd/assets/42897904/f9e61b7e-a26e-43cf-94ab-4466a8da049a)
